apiVersion: apps/v1
kind: Deployment
metadata:
  name: waterpricing
  namespace: "proj-gr4"
  labels:
    app: waterpricing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waterpricing
  template:
    metadata:
      labels:
        app: waterpricing
    spec:
      containers:
      - name: waterpricing
        image: 201608930/waterpricing:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata: 
  name: waterpricing
  namespace: "proj-gr4"
  labels:
    app: waterpricing
spec:
  selector:
    app: waterpricing
  ports:
    - port: 8080
      targetPort: 80
    
      
      
